openapi: 3.0.0
info:
  title: collateral management
  version: '1.0'
  contact:
    name: Al
    url: 'http://github.com/alvaroacev/api-spec'
  license:
    name: Apache
  description: 'These collateral report APIs are used to provide the details of the valuation of the collateral, that is, the valuation of securities collateral, cash collateral or other type of collateral, posted at a specific calculation date.'
servers:
  - url: 'http://localhost:3000'
paths:
  '/collaterals/{reportId}':
    parameters:
      - schema:
          type: string
        name: reportId
        in: path
        required: true
    get:
      summary: Get Collateral by ID
      tags:
        - Collateral Management
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Collateral'
              examples:
                example-1:
                  value:
                    report_id: Abcd123
                    date_time: '2019-08-24T14:15:22Z'
                    frequency: DAILY
                    currency: GBP
                    calculation_date: '1997-10-31'
                    obligation:
                      party_a: CHASGBLN
                      servicing_party_a: CHASGBLN
                      party_b: BARCGBLV
                      exposure_type: BFWD
                    agreement:
                      details: agreement description
                      identification: Abcd123-112
                      date: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-collateral-id
      description: Retrieves the collateral report with the matching report ID.
  /collaterals:
    get:
      summary: Your GET endpoint
      tags:
        - Collateral Management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Collateral'
              examples:
                example-1:
                  value:
                    - report_id: Abcd123
                      date_time: '2019-08-24T14:15:22Z'
                      frequency: DAILY
                      currency: GBP
                      calculation_date: '1997-10-31'
                      obligation:
                        party_a: CHASGBLN
                        servicing_party_a: CHASGBLN
                        party_b: BARCGBLV
                        exposure_type: BFWD
                      agreement:
                        details: agreement description
                        identification: Abcd123-112
                        date: '2019-08-24'
                    - report_id: 1664-FR
                      date_time: '2020-08-24T14:15:22Z'
                      frequency: DAILY
                      currency: GBP
                      calculation_date: '1997-10-31'
                      obligation:
                        party_a: CHASGBLN
                        servicing_party_a: CHASGBLN
                        party_b: BARCGBLV
                        exposure_type: BFWD
                      agreement:
                        details: agreement description
                        identification: Abcd123-112
                        date: '2019-08-24'
            application/xml:
              schema:
                type: object
                properties: {}
      operationId: get-collaterals
      description: Retrieves all the collateral reports or the ones matching any of the queries parameters
      parameters:
        - schema:
            type: string
            format: date
            example: '2020-10-30'
          in: query
          name: creation_date
          description: Date at which the report was created.
        - schema:
            type: string
            enum:
              - Daily
              - Intra_Day
              - On_Demand
            example: Daily
          in: query
          description: Frequency of the report.
          name: frequency
        - schema:
            type: string
            pattern: '[A-Z]{3,3}'
            example: GBP
          in: query
          description: Indicates the currency used for the calculation of the guarantee fund.
          name: currency
    parameters: []
components:
  schemas:
    Collateral:
      title: Collateral
      type: object
      description: 'Provides the details of the valuation of the collateral, that is, the valuation of securities collateral, cash collateral or other type of collateral, posted at a specific calculation date.'
      x-examples:
        example-1:
          report_id: Abcd123
          date_time: '2019-08-24T14:15:22Z'
          frequency: DAILY
          currency: GBP
          calculation_date: '1997-10-31'
          obligation:
            party_a: CHASGBLN
            servicing_party_a: string
            party_b: BARCGBLV
            exposure_type: BFWD
          agreement:
            details: agreement description
            identification: Abcd123-112
            date: '2019-08-24'
      properties:
        report_id:
          type: string
          description: Unique identification of the report.
        date_time:
          format: date-time
          type: string
        frequency:
          type: string
          enum:
            - DAILY
            - INTRADAY
            - ONDEMAND
        currency:
          type: string
          pattern: '[A-Z]{3,3}'
        calculation_date:
          type: string
          format: date
          example: '1997-10-31'
        obligation:
          type: object
          description: Set to true if the user's email has been verified.
          required:
            - party_a
            - party_b
          properties:
            party_a:
              type: string
              pattern: '[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}'
              description: Defines one of the entities associated with the collateral agreement.
            servicing_party_a:
              type: string
              pattern: '[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}'
              description: Specifies the party that is acting on behalf of party A and that offers collateral management services.
            party_b:
              type: string
              description: Defines the other entity associated with the collateral agreement.
              maxLength: 35
            exposure_type:
              type: string
              enum:
                - BFWD
                - PAYM
                - CCPC
              description: Specifies the underlying business area or type of trade causing the collateral movement.
        agreement:
          description: Agreement details for the over the counter market.
          type: object
          properties:
            details:
              type: string
            identification:
              type: string
            date:
              type: string
              format: date
          required:
            - identification
      required:
        - report_id
        - date_time
        - frequency
        - currency
        - obligation
  securitySchemes:
    API Key - 1:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://api.swift.com/oauth2/v1/token'
          refreshUrl: 'https://api.swift.com/oauth2/v1/token'
          scopes: {}
        password:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
      description: request token and refresh token on same URL
tags:
  - name: Collateral Management
